name: main
description: Main page
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../../common/base
  home:
    path: ../../features/home
  search:
    path: ../../features/search
  order:
    path: ../../features/order
  profile:
    path: ../../features/profile

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: