name: api
description: Backend API module
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  food_api_client:
    path: ../../../../openapi/flutter/api
  dio: '>=4.0.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: